from __future__ import unicode_literals

from django.contrib.gis.db import models

class AfgMettClim1KmChelsaBioclim(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    bio1 = models.FloatField(blank=True, null=True)
    bio2 = models.FloatField(blank=True, null=True)
    bio3 = models.FloatField(blank=True, null=True)
    bio4 = models.FloatField(blank=True, null=True)
    bio5 = models.FloatField(blank=True, null=True)
    bio6 = models.FloatField(blank=True, null=True)
    bio7 = models.FloatField(blank=True, null=True)
    bio8 = models.FloatField(blank=True, null=True)
    bio9 = models.FloatField(blank=True, null=True)
    bio10 = models.FloatField(blank=True, null=True)
    bio11 = models.FloatField(blank=True, null=True)
    bio12 = models.IntegerField(blank=True, null=True)
    bio13 = models.IntegerField(blank=True, null=True)
    bio14 = models.IntegerField(blank=True, null=True)
    bio15 = models.IntegerField(blank=True, null=True)
    bio16 = models.IntegerField(blank=True, null=True)
    bio17 = models.IntegerField(blank=True, null=True)
    bio18 = models.IntegerField(blank=True, null=True)
    bio19 = models.IntegerField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_clim_1km_chelsa_bioclim'

class AfgMettClim1KmWorldclimBioclim2050Rpc26(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    bio1 = models.FloatField(blank=True, null=True)
    bio2 = models.FloatField(blank=True, null=True)
    bio3 = models.FloatField(blank=True, null=True)
    bio4 = models.FloatField(blank=True, null=True)
    bio5 = models.FloatField(blank=True, null=True)
    bio6 = models.FloatField(blank=True, null=True)
    bio7 = models.FloatField(blank=True, null=True)
    bio8 = models.FloatField(blank=True, null=True)
    bio9 = models.FloatField(blank=True, null=True)
    bio10 = models.FloatField(blank=True, null=True)
    bio11 = models.FloatField(blank=True, null=True)
    bio12 = models.FloatField(blank=True, null=True)
    bio13 = models.FloatField(blank=True, null=True)
    bio14 = models.FloatField(blank=True, null=True)
    bio15 = models.FloatField(blank=True, null=True)
    bio16 = models.FloatField(blank=True, null=True)
    bio17 = models.FloatField(blank=True, null=True)
    bio18 = models.FloatField(blank=True, null=True)
    bio19 = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_clim_1km_worldclim_bioclim_2050_rpc26'

class AfgMettClim1KmWorldclimBioclim2050Rpc45(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    bio1 = models.FloatField(blank=True, null=True)
    bio2 = models.FloatField(blank=True, null=True)
    bio3 = models.FloatField(blank=True, null=True)
    bio4 = models.FloatField(blank=True, null=True)
    bio5 = models.FloatField(blank=True, null=True)
    bio6 = models.FloatField(blank=True, null=True)
    bio7 = models.FloatField(blank=True, null=True)
    bio8 = models.FloatField(blank=True, null=True)
    bio9 = models.FloatField(blank=True, null=True)
    bio10 = models.FloatField(blank=True, null=True)
    bio11 = models.FloatField(blank=True, null=True)
    bio12 = models.FloatField(blank=True, null=True)
    bio13 = models.FloatField(blank=True, null=True)
    bio14 = models.FloatField(blank=True, null=True)
    bio15 = models.FloatField(blank=True, null=True)
    bio16 = models.FloatField(blank=True, null=True)
    bio17 = models.FloatField(blank=True, null=True)
    bio18 = models.FloatField(blank=True, null=True)
    bio19 = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_clim_1km_worldclim_bioclim_2050_rpc45'

class AfgMettClim1KmWorldclimBioclim2050Rpc85(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    bio1 = models.FloatField(blank=True, null=True)
    bio2 = models.FloatField(blank=True, null=True)
    bio3 = models.FloatField(blank=True, null=True)
    bio4 = models.FloatField(blank=True, null=True)
    bio5 = models.FloatField(blank=True, null=True)
    bio6 = models.FloatField(blank=True, null=True)
    bio7 = models.FloatField(blank=True, null=True)
    bio8 = models.FloatField(blank=True, null=True)
    bio9 = models.FloatField(blank=True, null=True)
    bio10 = models.FloatField(blank=True, null=True)
    bio11 = models.FloatField(blank=True, null=True)
    bio12 = models.FloatField(blank=True, null=True)
    bio13 = models.FloatField(blank=True, null=True)
    bio14 = models.FloatField(blank=True, null=True)
    bio15 = models.FloatField(blank=True, null=True)
    bio16 = models.FloatField(blank=True, null=True)
    bio17 = models.FloatField(blank=True, null=True)
    bio18 = models.FloatField(blank=True, null=True)
    bio19 = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_clim_1km_worldclim_bioclim_2050_rpc85'

class AfgMettClim1KmWorldclimBioclim2070Rpc26(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    bio1 = models.FloatField(blank=True, null=True)
    bio2 = models.FloatField(blank=True, null=True)
    bio3 = models.FloatField(blank=True, null=True)
    bio4 = models.FloatField(blank=True, null=True)
    bio5 = models.FloatField(blank=True, null=True)
    bio6 = models.FloatField(blank=True, null=True)
    bio7 = models.FloatField(blank=True, null=True)
    bio8 = models.FloatField(blank=True, null=True)
    bio9 = models.FloatField(blank=True, null=True)
    bio10 = models.FloatField(blank=True, null=True)
    bio11 = models.FloatField(blank=True, null=True)
    bio12 = models.FloatField(blank=True, null=True)
    bio13 = models.FloatField(blank=True, null=True)
    bio14 = models.FloatField(blank=True, null=True)
    bio15 = models.FloatField(blank=True, null=True)
    bio16 = models.FloatField(blank=True, null=True)
    bio17 = models.FloatField(blank=True, null=True)
    bio18 = models.FloatField(blank=True, null=True)
    bio19 = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_clim_1km_worldclim_bioclim_2070_rpc26'

class AfgMettClim1KmWorldclimBioclim2070Rpc45(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    bio1 = models.FloatField(blank=True, null=True)
    bio2 = models.FloatField(blank=True, null=True)
    bio3 = models.FloatField(blank=True, null=True)
    bio4 = models.FloatField(blank=True, null=True)
    bio5 = models.FloatField(blank=True, null=True)
    bio6 = models.FloatField(blank=True, null=True)
    bio7 = models.FloatField(blank=True, null=True)
    bio8 = models.FloatField(blank=True, null=True)
    bio9 = models.FloatField(blank=True, null=True)
    bio10 = models.FloatField(blank=True, null=True)
    bio11 = models.FloatField(blank=True, null=True)
    bio12 = models.FloatField(blank=True, null=True)
    bio13 = models.FloatField(blank=True, null=True)
    bio14 = models.FloatField(blank=True, null=True)
    bio15 = models.FloatField(blank=True, null=True)
    bio16 = models.FloatField(blank=True, null=True)
    bio17 = models.FloatField(blank=True, null=True)
    bio18 = models.FloatField(blank=True, null=True)
    bio19 = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_clim_1km_worldclim_bioclim_2070_rpc45'

class AfgMettClim1KmWorldclimBioclim2070Rpc85(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    bio1 = models.FloatField(blank=True, null=True)
    bio2 = models.FloatField(blank=True, null=True)
    bio3 = models.FloatField(blank=True, null=True)
    bio4 = models.FloatField(blank=True, null=True)
    bio5 = models.FloatField(blank=True, null=True)
    bio6 = models.FloatField(blank=True, null=True)
    bio7 = models.FloatField(blank=True, null=True)
    bio8 = models.FloatField(blank=True, null=True)
    bio9 = models.FloatField(blank=True, null=True)
    bio10 = models.FloatField(blank=True, null=True)
    bio11 = models.FloatField(blank=True, null=True)
    bio12 = models.FloatField(blank=True, null=True)
    bio13 = models.FloatField(blank=True, null=True)
    bio14 = models.FloatField(blank=True, null=True)
    bio15 = models.FloatField(blank=True, null=True)
    bio16 = models.FloatField(blank=True, null=True)
    bio17 = models.FloatField(blank=True, null=True)
    bio18 = models.FloatField(blank=True, null=True)
    bio19 = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_clim_1km_worldclim_bioclim_2070_rpc85'

class AfgMettClimperc1KmChelsaPrec(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    january = models.FloatField(blank=True, null=True)
    february = models.FloatField(blank=True, null=True)
    march = models.FloatField(blank=True, null=True)
    april = models.FloatField(blank=True, null=True)
    may = models.FloatField(blank=True, null=True)
    june = models.FloatField(blank=True, null=True)
    july = models.FloatField(blank=True, null=True)
    august = models.FloatField(blank=True, null=True)
    september = models.FloatField(blank=True, null=True)
    october = models.FloatField(blank=True, null=True)
    november = models.FloatField(blank=True, null=True)
    december = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_climperc_1km_chelsa_prec'

class AfgMettClimtemp1KmChelsaTempavg(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    january = models.FloatField(blank=True, null=True)
    february = models.FloatField(blank=True, null=True)
    march = models.FloatField(blank=True, null=True)
    april = models.FloatField(blank=True, null=True)
    may = models.FloatField(blank=True, null=True)
    june = models.FloatField(blank=True, null=True)
    july = models.FloatField(blank=True, null=True)
    august = models.FloatField(blank=True, null=True)
    september = models.FloatField(blank=True, null=True)
    october = models.FloatField(blank=True, null=True)
    november = models.FloatField(blank=True, null=True)
    december = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_climtemp_1km_chelsa_tempavg'

class AfgMettClimtemp1KmChelsaTempmax(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    january = models.FloatField(blank=True, null=True)
    february = models.FloatField(blank=True, null=True)
    march = models.FloatField(blank=True, null=True)
    april = models.FloatField(blank=True, null=True)
    may = models.FloatField(blank=True, null=True)
    june = models.FloatField(blank=True, null=True)
    july = models.FloatField(blank=True, null=True)
    august = models.FloatField(blank=True, null=True)
    september = models.FloatField(blank=True, null=True)
    october = models.FloatField(blank=True, null=True)
    november = models.FloatField(blank=True, null=True)
    december = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_climtemp_1km_chelsa_tempmax'

class AfgMettClimtemp1KmChelsaTempmin(models.Model):
    ogc_fid = models.IntegerField(primary_key=True)
    wkb_geometry = models.PointField(blank=True, null=True)
    lat_y = models.FloatField(blank=True, null=True)
    lon_x = models.FloatField(blank=True, null=True)
    dist_code = models.IntegerField(blank=True, null=True)
    prov_code = models.IntegerField(blank=True, null=True)
    vuid = models.CharField(max_length=50, blank=True)
    january = models.FloatField(blank=True, null=True)
    february = models.FloatField(blank=True, null=True)
    march = models.FloatField(blank=True, null=True)
    april = models.FloatField(blank=True, null=True)
    may = models.FloatField(blank=True, null=True)
    june = models.FloatField(blank=True, null=True)
    july = models.FloatField(blank=True, null=True)
    august = models.FloatField(blank=True, null=True)
    september = models.FloatField(blank=True, null=True)
    october = models.FloatField(blank=True, null=True)
    november = models.FloatField(blank=True, null=True)
    december = models.FloatField(blank=True, null=True)
    objects = models.GeoManager()
    class Meta:
        managed = True
        db_table = 'afg_mett_climtemp_1km_chelsa_tempmin'
